efgs:
  downloader:
    certs:
      nbbs-location: nbbs_eu # contains PRIVATE KEY and CERTIFICATE
      nbtls-location: nbtls_eu # contains PRIVATE KEY and CERTIFICATE
    db:
      processed-field: processed
      collections:
        batch-tag: processedBatchTags
    days-to-check-before-now: 14
