efgs:
  downloader:
    certs:
      nbbs-location: nbbs
      nbtls-location: nbtls
    db:
      last-batch-tag-field: lastBatchTag
      collections:
        batch-tag: processedBatchTags
  api: https://efgs.koronazglowy.com/diagnosiskeys
  message:
    project-id: protego-fb-dev
    topic-id: firebase-subscription-uploadDiagnosisKeysSubscriber-europe-west1
