efgs:
  downloader:
    certs:
      nbbs-location: nbbs # contains PRIVATE KEY and CERTIFICATE
      nbtls-location: nbtls # contains PRIVATE KEY and CERTIFICATE
    db:
      last-batch-tag-field: lastBatchTag
      collections:
        batch-tag: processedBatchTags
  api: https://efgs.koronazglowy.com/diagnosiskeys
  message:
    project-id: protego-fb-dev
    topic-id: firebase-test-europe-west1

