efgs:
  downloader:
    certs:
      nbbs-location: nbbs_eu # contains PRIVATE KEY and CERTIFICATE
      nbtls-location: nbtls_eu # contains PRIVATE KEY and CERTIFICATE
    db:
      processed-field: processed
      collections:
        batch-tag: processedBatchTags
    days-to-check-before-now: 14
  api: https://test-efgs-ws.tech.ec.europa.eu/diagnosiskeys
#  api: https://efgs.koronazglowy.com/diagnosiskeys
  message:
    project-id: protego-fb-dev
    topic-id: firebase-subscription-uploadDiagnosisKeysSubscriber-europe-west1
