version: "3"
services:
  node_dev_env:
    build: .
    container_name: cloud-backend
    volumes:
      - ../:/app
    command: tail -f /dev/null
    ports:
      - "5001:5001"
      - "4000:4000"
      - "9005:9005"
